### ISSUE TITLE
deploy 失敗

### ISSUE THREAD

**Issue by st474ddr** [Tzuhui/actions-test#1]
不好意思
我是透過近期分享影片找到大大您的分享

我在deploy的時候遇到狀況
由於現在JamesIves/github-pages-deploy-action@master 被branch改名稱了
所以我使用的是JamesIves/github-pages-deploy-action@main (master壞壞)

其他部份我完全是一樣的yml
可是deploy那關會跳出
`
File not found: '/home/runner/work/_actions/JamesIves/github-pages-deploy-action/main/lib/main.js'
`

我仔細比對我們的CI流程
發現您有一個build docker的階段
不知道是不是差在這裡
但我連fork您的repo都沒辦法成功build完

可以請大大指點迷津

**Comment by Tzuhui** [comment]
@st474ddr 
你好，感謝回報～
已修改 [main.yml](https://github.com/Tzuhui/actions-test/blob/master/.github/workflows/main.yml)，目前測試已成功部署哩

**Comment by st474ddr** [comment]
感謝回覆
我也成功能deploy了
我之前也有稍微查一下資料
貌似是env用法被改掉 現在都要使用with?

冒昧再請教一個問題
ACCESS_TOKEN 在with下還有功用嗎?
我發現就我算我拿掉ACCESS_TOKEN 還是可以部署成功

**Comment by Tzuhui** [comment]
如果部署到同一個 repo 可以拿掉
如果是會部署到另一個 repo 就需要加上

**Comment by st474ddr** [comment]
感謝
